version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: gegarron:latest
    container_name: gegarron
    restart: unless-stopped
    ports:
      - '80:80'
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - nginx_cache:/var/cache/nginx
      - nginx_logs:/var/log/nginx
    networks:
      - app_network
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://localhost/health',
        ]
      interval: 30s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

volumes:
  nginx_cache:
  nginx_logs:

networks:
  app_network:
    driver: bridge
